[2023-04-10 16:37:23,353][moc][INFO][color_logger.py:203] Logfile: /home/chenyiqi/wafer_scale_chip_dse_framework/logs/moc_2023-04-10-16-37-23-352845.log
[2023-04-10 16:37:23,356][moc][WARNING][generic_smbo.py:386] Exception when calling objective function: local variable '_history' referenced before assignment
config: Configuration(values={
  'fidelity': 1,
  'var00': 48,
  'var01': 2048,
  'var02': 128,
  'var03': 64,
  'var04': 4,
  'var05': 4,
  'var06': 1,
  'var07': 40,
  'var08': 24,
  'var09': 900,
  'var10': 8,
  'var11': 9,
})

